Algoritmo "Questão 05"
//5) Fazer um programa que pergunte o salário de um funcionário e
// apresente este salário com um aumento de 15%
Var
  salario,aumento: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva(" Informe o salário:")
  leia(salario)
  
    aumento <- salario * 0.15
    
   escreva( "O salário com o aumento de 15% é R$",(salario+aumento))


Fimalgoritmo