Algoritmo "Questão 04"
// 4) Fazer um programa que pergunte um número inteiro e
// apresente o seu antecessor e seu sucessor.

Var
// Seção de Declarações das variáveis 
   num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreval("Informe um número:")
       leia(num)
       escreval(" o antecessor de" , num, " é " , (num - 1))
       escreval(" o sucessor de ", num, " é " , (num + 1))

Fimalgoritmo